### ISSUE TITLE
Change session store

### ISSUE THREAD

**Issue by cnasikas** [decrypto-org/blockchain-course#12]
https://github.com/expressjs/session/blob/master/README.md#compatible-session-stores

**Comment by cnasikas** [comment]
@dionyziz The session store we are using now is the memory store and it is only suitable for development. We should choose a session store that we should use in production.

**Comment by dionyziz** [comment]
Let's store it in our database since we have one? I guess this is for our
own deployment purposes only, right?

**Comment by cnasikas** [comment]
The store is declared as

```
  app.use(session({
    store: <your_store> 
  }))
```

I do not like the idea that the store will be bounded to a particular dbms. I agree that the correct one for our purpose is the postgres store. Any suggestion to make it generic or somehow not enforce a dbms ?
