### ISSUE TITLE
Installation instructions don't work

### ISSUE THREAD

**Issue by OrfeasLitos** [decrypto-org/blockchain-course#16]
2nd command of 3rd bullet (`./node_modules/.bin/run.env ./node_modules/.bin/sequelize db:migrate`) doesn't cooperate:
```
$ ./node_modules/.bin/run.env ./node_modules/.bin/sequelize db:migrate

Sequelize CLI [Node: 11.6.0, CLI: 4.1.1, ORM: 4.39.0]

Loaded configuration file "config/config.js".
Using environment "development".

ERROR: Error parsing url: undefined
```

**Comment by OrfeasLitos** [comment]
Also the 2nd `cd db` (bullet 3) didn't work, as I was already in the `db` directory

**Comment by cnasikas** [comment]
Sorry the order of the commands is wrong. You should first modify the `.env` variables accordingly:

`Copy .env-template to .env and modify the variables`

> Also the 2nd `cd db` (bullet 3) didn't work, as I was already in the `db` directory

The assumption is that you are in repository folder every time you execute a command. Its a bit of redundant but I think it is clearer and not confusing.

**Comment by OrfeasLitos** [comment]
If you assume all commands are executed from the outermost directory, then you should point this out explicitly. But IMO the most user-friendly way is to write a series of commands that can be (blindly) executed sequentially and reach a working installation.

**Comment by OrfeasLitos** [comment]
Also a user that just found the repo cannot readily understand
> and modify the variables accordingly
I'd have to dig a lot to understand what values are valid for these environment variables. I'd rather have a sensible default `.env` and have to modify it only when I need to (i.e. when I understand what is the purpose of these environment variables).

**Comment by OrfeasLitos** [comment]
Lastly, there are tools that automate installing and linking nested repositories (such as https://github.com/lerna/lerna), so that users do not have to repeat steps. Or, if such tools are too much hassle, a simple bash script that executes the commands for the user (or a Makefile) could also do the job. @dionyziz, @dimkarakostas. @pkakelas you can suggest other ways of simplifying installation.

**Comment by OrfeasLitos** [comment]
One more thing, after copying `.env-template` to `.env`, I got the following error:
```
$ ./node_modules/.bin/run.env ./node_modules/.bin/sequelize db:migrate

Sequelize CLI [Node: 11.6.0, CLI: 4.1.1, ORM: 4.39.0]

Loaded configuration file "config/config.js".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13

ERROR: connect ECONNREFUSED 127.0.0.1:5432
```
this may be relevant:
```
$ cat .env
DB_URI=postgres://root:root@localhost/blockchain_course
PROVIDER=http://localhost:7545
ASSIGNMENT_FOLDER=
```

**Comment by cnasikas** [comment]
> If you assume all commands are executed from the outermost directory, then you should point this out explicitly. But IMO the most user-friendly way is to write a series of commands that can be (blindly) executed sequentially and reach a working installation.

Ok, I will change accordingly.



> Also a user that just found the repo cannot readily understand
> 
> > and modify the variables accordingly
> > I'd have to dig a lot to understand what values are valid for these environment variables. I'd rather have a sensible default `.env` and have to modify it only when I need to (i.e. when I understand what is the purpose of these environment variables).

The environment variables are sensible enough. Because the project depends on sequelize (and an ethereum provider if you want to use `SolidityJudge`) you have install postgres, create a db named blockchain_course and grant at least permissions for root to `blockchain_course` db. That's why you get `ERROR: connect ECONNREFUSED 127.0.0.1:5432`.

 I am aware that the instructions doesn't mention anything at all and **should**.

> Lastly, there are tools that automate installing and linking nested repositories (such as https://github.com/lerna/lerna), so that users do not have to repeat steps. Or, if such tools are too much hassle, a simple bash script that executes the commands for the user (or a Makefile) could also do the job. @dionyziz, @dimkarakostas. @pkakelas you can suggest other ways of simplifying installation.

Please open another issue regarding this issue.

**Comment by cnasikas** [comment]
I update the instructions to reflect your observations. If you have any other suggestion or problem feel free to post. Thanks!
