### ISSUE TITLE
assignments folder should be empty

### ISSUE THREAD

**Issue by dionyziz** [decrypto-org/blockchain-course#31]
This allows it to be its separate submodule

**Comment by cnasikas** [comment]
What do you mean ?

**Comment by dionyziz** [comment]
The folder `db/assignments` contains some files in the current repo. In particular, it contains an `index.js` and a `judge` folder. These should be moved out of the `db/assignments` folder and into somewhere else (e.g. `db/judge`?) Then the `db/assignments` folder will be empty. That way, if someone has another git repository where their assignments are maintained, it can be included as a git submodule and cloning can be done directly into the empty `db/assignments` folder.

**Comment by cnasikas** [comment]
`index.js` is crucial for assignments loading. Where it should be placed ?

**Comment by cnasikas** [comment]
Nevermind, thought a better solution. `index.js` is not needed.
