### ISSUE TITLE
Default assignments folder in .env is incorrect

### ISSUE THREAD

**Issue by dionyziz** [decrypto-org/blockchain-course#32]
It is `./assignments`, but this refers to `api/db/assignments`, while the correct folder is `db/assignments` (outside the api dir).

**Comment by cnasikas** [comment]
Inside `db/models/custom/assignment.js` in line 1 the assignments' folder is declared as 

`const ASSIGNMENT_FOLDER = process.env.ASSIGNMENT_FOLDER || '../../assignments'`

The correct should be `../../assignments` but it seems redundant to declare it again. I think is better to leave it empty. What do you thing ?

**Comment by dionyziz** [comment]
Either way is fine, as long as the default environment works out of the box.
