### ISSUE TITLE
Change solved status when a wrong solution is submitted

### ISSUE THREAD

**Issue by cnasikas** [decrypto-org/blockchain-course#36]
The default db value of solved column is false. When a user submits a correct solution the solved status variable changes to true. If the user submits another wrong solution the status is not changed but the new solution (wrong in this example) is saved.

**Comment by OrfeasLitos** [comment]
In my opinion, if a player has already solved the exercise in the past and they try again with a wrong solution, the status shouldn't be changed.

If they try for the first time and fail, then the status could or could not change. Let's just ensure that, if we decide to have it change, the player doesn't think that they cannot try again.

**Comment by cnasikas** [comment]
Ok! I agree that it will be confusing, you are right. My main concern is how we will handle a submitted solution ? What if in the future we introduced a tiered grading system that have a minimum pass (solved) grade but then the user can improve her score ?

A solution to this will be to not save the user's solution if it is a failed one and save otherwise. What do you think ?

**Comment by dionyziz** [comment]
Just keep the best solution so far.

**Comment by cnasikas** [comment]
How you define the best solution ? For the moment the grader is a pass or fail system.
